title: "Odile Franchet — Cybersécurité & Facteur humain"
theme: jekyll-theme-cayman
markdown: kramdown

header_pages:
  - index.md
  - apropos.md
  - prestations.md
  - formation.md
  - projets.md
  - blog.md
  
